### ISSUE TITLE
About scroll in UI

### ISSUE THREAD

**Issue by lichaozhy** [lemonce/probe-simple-report#1]
- [x] Log area independent scrolling
- [x] Code area independent scrolling
- [x] Code font-size 12px
- [x] Add top tip to the top of each area
- [x] log area fixed width 300px. https://github.com/lemonce/probe-simple-report/commit/01cacba7135dd90791b226e9cab7c1e912a0c2d6
- [x] case list fixed width 250px. https://github.com/lemonce/probe-simple-report/commit/01cacba7135dd90791b226e9cab7c1e912a0c2d6
- [x] code use the remaining area & ovflow:auto. https://github.com/lemonce/probe-simple-report/commit/01cacba7135dd90791b226e9cab7c1e912a0c2d6

**Comment by steambap** [comment]
Please be specific about "top-tip"

**Comment by steambap** [comment]
https://github.com/lemonce/probe-simple-report/commit/01cacba7135dd90791b226e9cab7c1e912a0c2d6
