### ISSUE TITLE
Log card

### ISSUE THREAD

**Issue by lichaozhy** [lemonce/probe-simple-report#2]
- [ ] Add instruction icon
- [ ] Add action icon
- [x] Duration time format to 'mm:ss.ssss'
- [x] All log (like type:start & type:end ) can be selected with highlight
- [ ] add all properties of a logData to the view.(action.duration...)

**Comment by steambap** [comment]
https://github.com/lemonce/probe-simple-report/commit/a8fa94c3f4878b13ed0739fe6896839e31b39284
